// Generated by https://quicktype.io

export interface Fixtures {
    get:        string;
    parameters: Parameters;
    errors:     any[];
    results:    number;
    paging:     Paging;
    response:   Response[];
}

interface Paging {
    current: number;
    total:   number;
}

interface Parameters {
    league: string;
    season: string;
}

interface Response {
    fixture: Fixture;
    league:  League;
    teams:   Goals;
    goals:   Goals;
    score:   Score;
}

interface Fixture {
    id:        number;
    referee:   null | string;
    timezone:  Timezone;
    date:      string;
    timestamp: number;
    periods:   Periods;
    venue:     Venue;
    status:    Status;
}

interface Periods {
    first:  number | null;
    second: number | null;
}

interface Status {
    long:    Long;
    short:   Short;
    elapsed: number | null;
}

enum Long {
    MatchFinished = "Match Finished",
    MatchPostponed = "Match Postponed",
    NotStarted = "Not Started",
}

enum Short {
    Ft = "FT",
    NS = "NS",
    Pst = "PST",
}

enum Timezone {
    UTC = "UTC",
}

interface Venue {
    id:   number;
    name: string;
    city: City;
}

enum City {
    Birmingham = "Birmingham",
    BrentfordMiddlesex = "Brentford, Middlesex",
    Burnley = "Burnley",
    FalmerEastSussex = "Falmer, East Sussex",
    LeedsWestYorkshire = "Leeds, West Yorkshire",
    LeicesterLeicestershire = "Leicester, Leicestershire",
    Liverpool = "Liverpool",
    London = "London",
    Manchester = "Manchester",
    NewcastleUponTyne = "Newcastle upon Tyne",
    NorwichNorfolk = "Norwich, Norfolk",
    SouthamptonHampshire = "Southampton, Hampshire",
    Watford = "Watford",
    WolverhamptonWestMidlands = "Wolverhampton, West Midlands",
}

 interface Goals {
    home: AwayClass | number | null;
    away: AwayClass | number | null;
}

 interface AwayClass {
    id:     number;
    name:   AwayName;
    logo:   string;
    winner: boolean | null;
}

 enum AwayName {
    Arsenal = "Arsenal",
    AstonVilla = "Aston Villa",
    Brentford = "Brentford",
    Brighton = "Brighton",
    Burnley = "Burnley",
    Chelsea = "Chelsea",
    CrystalPalace = "Crystal Palace",
    Everton = "Everton",
    Leeds = "Leeds",
    Leicester = "Leicester",
    Liverpool = "Liverpool",
    ManchesterCity = "Manchester City",
    ManchesterUnited = "Manchester United",
    Newcastle = "Newcastle",
    Norwich = "Norwich",
    Southampton = "Southampton",
    Tottenham = "Tottenham",
    Watford = "Watford",
    WestHam = "West Ham",
    Wolves = "Wolves",
}

 interface League {
    id:      number;
    name:    LeagueName;
    country: Country;
    logo:    string;
    flag:    string;
    season:  number;
    round:   string;
}

 enum Country {
    England = "England",
}

 enum LeagueName {
    PremierLeague = "Premier League",
}

 interface Score {
    halftime:  Goals;
    fulltime:  Goals;
    extratime: Goals;
    penalty:   Goals;
}
